version: '3'

services:
  
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    ports:
      - "5000:80"
  # db:
  #   restart: always
  #   image: mysql:8.0.25
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456789
  #   volumes:
  #     - /usr/local/docker/mysql:/var/lib/mysql
      
